import { Doctor } from "./types";

export const doctors: Doctor[] = [
  {
    id: "1",
    name: "Dr. Lakshmi Sindhura Kakani",
    specialization: "General Physician / Internal Medicine Specialist",
    degrees: ["MBBS", "MD (General Medicine)"],
    experience: 10,
    location: "Andhra Pradesh Visakhapatnam",
    hospital: "Apollo 24|7 Virtual Clinic",
    fees: {
      online: 649,
    },
    availability: {
      online: true,
      onlineInMinutes: 2,
    },
    avatar: "/doctors/doctor1.webp",
    badges: ["Doctor of the Hour"],
  },
  {
    id: "2",
    name: "Dr. Chethan T L",
    specialization: "General Physician / Internal Medicine Specialist",
    degrees: ["MBBS", "MD", "DNB (General Medicine)"],
    experience: 5,
    location: "Bengaluru",
    hospital: "Apollo Medical Center, Marathahalli",
    fees: {
      online: 550,
      cashback: 83,
    },
    availability: {
      online: true,
      onlineInMinutes: 1,
    },
    avatar: "/doctors/doctor2.webp",
  },
  {
    id: "3",
    name: "Dr. Aakash Garg",
    specialization: "Gastroenterology / Internal Medicine",
    degrees: ["MBBS", "MD", "DNB (Gastroenterology)"],
    experience: 12,
    location: "Bilaspur",
    hospital: "Apollo Hospitals Bilaspur",
    fees: {
      online: 800,
      offline: 800,
      cashback: 40,
    },
    availability: {
      offline: true,
      offlineInMinutes: 30,
    },
    rating: {
      value: 98,
      patients: 125,
    },
    avatar: "/doctors/doctor3.webp",
  },
  {
    id: "4",
    name: "Dr. Hariprasath J",
    specialization: "General Physician / Internal Medicine Specialist",
    degrees: ["MD (Gen Med)", "FCPP", "DIP (Diabetology)"],
    experience: 19,
    location: "Chennai",
    hospital: "Apollo First Med Hospitals",
    fees: {
      online: 900,
      offline: 900,
      cashback: 135,
      noBookingFees: true,
    },
    availability: {
      online: true,
      offline: true,
      onlineInMinutes: 1,
      offlineInMinutes: 1,
    },
    rating: {
      value: 93,
      patients: 175,
    },
    avatar: "/doctors/doctor4.webp",
  },
  {
    id: "5",
    name: "Dr. Sujay P R",
    specialization: "General Physician / Internal Medicine Specialist",
    degrees: ["MBBS"],
    experience: 3,
    location: "Bengaluru",
    hospital: "Prestige Shantiniketan - Society Clinic",
    fees: {
      online: 400,
      cashback: 40,
    },
    availability: {
      onlineInMinutes: 2,
    },
    avatar: "/doctors/doctor5.webp",
  },
  {
    id: "6",
    name: "Dr. Karan Goel",
    specialization: "General Physician / Paediatrics",
    degrees: ["MBBS", "MD (Paediatrics)"],
    experience: 11,
    location: "Kolkata",
    hospital: "Little Steps Clinic",
    fees: {
      online: 500,
      offline: 500,
    },
    availability: {
      onlineInMinutes: 12,
      offlineInMinutes: 12,
    },
    avatar: "/doctors/doctor6.webp",
  },
  {
    id: "7",
    name: "Dr. Sumanjita Bora",
    specialization: "Family Physician",
    degrees: ["MBBS", "PGDCC"],
    experience: 7,
    location: "Bengaluru",
    hospital: "Apollo Multispeciality Clinic",
    fees: {
      online: 938,
      offline: 550,
    },
    availability: {
        online: true,
        offline: true,
        onlineInMinutes: 1,
        offlineInMinutes: 1,
    },
    avatar: "/doctors/doctor7.webp",
  },
];
